### ISSUE TITLE
Conditional system graphs

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#103]
# Requirements
- [x] Conditional CPU graph
* Green `#6aa84f` = 0 - 25%
* Yellow `#f1c232` = 25 - 50%
* Orange `#e69138` = 50 - 75%
* Red `#cc0000` = 75% - 100% 
- [x] Conditional Memory graph
* Green `#6aa84f` = 0 - 25%
* Yellow `#f1c232` = 25 - 50%
* Orange `#e69138` = 50 - 75%
* Red `#cc0000` = 75% - 100% 
- [x] Conditional CPU Temp graph
* Green `#6aa84f` <122°F
* Yellow `#f1c232` = 122 - 140°F
* Orange `#e69138` = 140 - 176°F
* Red `#cc0000` = 176°F+
- [x] Upload speed
* Bright Green `#6aa84f` = 250+ megs
* Medium Green `#93c47d` = 150 - 250 megs
* Light Green `#b6d7a8` = 100 - 150 megs
* Yellow `#f1c232` = 100 megs
* Orange `#e69138` = 75 - 100 megs
* Red `#cc0000` = <75 megs
- [x] Download speed
* Bright Green `#6aa84f` = 250+ megs
* Medium Green `#93c47d` = 150 - 250 megs
* Light Green `#b6d7a8` = 100 - 150 megs
* Yellow `#f1c232` = 100 megs
* Orange `#e69138` = 75 - 100 megs
* Red `#cc0000` = <75 megs

### Dynamic line color

Have the graph change line color dynamically.
```
- type: custom:mini-graph-card
  entities:
    - sensor.sensor_temperature
  show:
    labels: true
  color_thresholds:
    - value: 20
      color: "#f39c12"
    - value: 21
      color: "#d35400"
    - value: 21.5
      color: "#c0392b"
```
![image](https://user-images.githubusercontent.com/2943783/99197918-46927a80-274a-11eb-9f61-4f19fdbc537e.png)
# Resources
* [Lovelace Mini Graph Card](https://github.com/kalkih/mini-graph-card)
