### ISSUE TITLE
Volume up script

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#203]
# Requirements
```
volume_down:
  alias: Volume Down
  sequence:
  - service: rest_command.volume_down
```
Dependent on #213 
# Resources
* #62
