### ISSUE TITLE
Volume down script

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#204]
# Requirements
```
volume_up:
  alias: Volume Up
  sequence:
  - service: rest_command.volume_up
```
# Resources
* #62
