### ISSUE TITLE
Navigate UP script

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#205]
# Requirements
```
nav_up:
  alias: Navigate Up
  sequence:
    - service: androidtv.adb_command
      data:
        entity_id: media_player.shield_tv
        command: "UP"
  mode: single
```
# Resources
[HA Android TV commands](https://www.home-assistant.io/integrations/androidtv/)
