### ISSUE TITLE
Navigate DOWN script

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#206]
# Requirements
```
nav_down:
  alias: Navigate Down
  sequence:
    - service: androidtv.adb_command
      data:
        entity_id: media_player.shield_tv
        command: "DOWN"
  mode: single
```
# Resources
[HA Android TV commands](https://www.home-assistant.io/integrations/androidtv/)
