### ISSUE TITLE
Navigate RIGHT script

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#207]
# Requirements
```
nav_right:
  alias: Navigate Right
  sequence:
    - service: androidtv.adb_command
      data:
        entity_id: media_player.shield_tv
        command: "RIGHT"
  mode: single
```
# Resources
[HA Android TV commands](https://www.home-assistant.io/integrations/androidtv/)
