### ISSUE TITLE
Navigate LEFT script

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#208]
# Requirements
```
nav_left:
  alias: Navigate Left
  sequence:
    - service: androidtv.adb_command
      data:
        entity_id: media_player.shield_tv
        command: "LEFT"
  mode: single
```
# Resources
[HA Android TV commands](https://www.home-assistant.io/integrations/androidtv/)
