### ISSUE TITLE
Navigate HOME script

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#209]
# Requirements
```
nav_home:
  alias: Navigate Home
  sequence:
    - service: androidtv.adb_command
      data:
        entity_id: media_player.shield_tv
        command: "HOME"
  mode: single
```
# Resources
[HA Android TV commands](https://www.home-assistant.io/integrations/androidtv/)
