### ISSUE TITLE
Navigate BACK script

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#210]
# Requirements
```
nav_back:
  alias: Navigate Back
  sequence:
    - service: androidtv.adb_command
      data:
        entity_id: media_player.shield_tv
        command: "BACK
  mode: single
```
# Resources
[HA Android TV commands](https://www.home-assistant.io/integrations/androidtv/)
