### ISSUE TITLE
ENTER script

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#211]
# Requirements
```
nav_enter:
  alias: Navigate Enter
  sequence:
    - service: androidtv.adb_command
      data:
        entity_id: media_player.shield_tv
        command: "ENTER"
  mode: single
```
# Resources
[HA Android TV commands](https://www.home-assistant.io/integrations/androidtv/)
