### ISSUE TITLE
POWER script

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#212]
# Requirements
```
toggle_power:
  alias: Toggle Shield Power
  sequence:
    - service: androidtv.adb_command
      data:
        entity_id: media_player.shield_tv
        command: "POWER"
  mode: single
```
# Resources
[HA Android TV commands](https://www.home-assistant.io/integrations/androidtv/)
