### ISSUE TITLE
rest_command.yaml

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#213]
# Requirements
```
set_volume:
  url: 'http://192.168.86.187/goform/formiPhoneAppDirect.xml?MV{{states("input_number.denon_volume").replace(".", "") }}'
volume_up:
  url: 'http://192.168.86.187/goform/formiPhoneAppDirect.xml?MVUP'
volume_down:
  url: 'http://192.168.86.187/goform/formiPhoneAppDirect.xml?MVDOWN'
volume_correct:
  url: 'http://192.168.86.187/goform/formiPhoneAppDirect.xml?MV35'
volume_mute:
  url:
av_menu_on:
  url:
av_menu_off:
  url: 
eco_on:
  url: 'http://192.168.86.187/goform/formiPhoneAppDirect.xml?ECOON'
eco_off:
  url: 'http://192.168.86.187/goform/formiPhoneAppDirect.xml?ECOOFF'
av_return:
  url: 
```
# Resources
