### ISSUE TITLE
ECO on script

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#214]
# Requirements
```
eco_on:
  alias: ECO Mode On
  sequence:
  - service: rest_command.eco_on
```
Dependent on #213 
# Resources
* #62
