### ISSUE TITLE
ECO off script

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#215]
# Requirements
```
eco_off:
  alias: ECO Mode Off
  sequence:
  - service: rest_command.eco_off
```
Dependent on #213 
# Resources
* #62
