### ISSUE TITLE
Create washer dashboard button

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#250]
https://github.com/theglus/Home-Assistant-Config/blob/caf5cef7b46af58a5bbf9ba85b01454ba3a03024/includes/lovelace/views/1_primary.yaml#L335-L338

# Requirements
- [ ] Install [SmartThinQ sensor](https://github.com/ollo69/ha-smartthinq-sensors) HACs integration.
- [ ] TBD

**Comment by theglus** [comment]
Utilize [entity attributes](https://github.com/phrz/lg-washer-dryer-card/blob/1807310cbbb544fe556ab95cbe324ab4faef3e72/washer-card.yaml#L90).    

```
card:
  type: entities
  entities:
    - entity: sensor.washer
      type: attribute
      attribute: current_course
      name: Current Course
      icon: 'mdi:tune-vertical-variant'
    - entity: sensor.washer
      type: attribute
      attribute: water_temp
      name: Water Temperature
      icon: 'mdi:coolant-temperature'
    - entity: sensor.washer
      type: attribute
      attribute: spin_speed
      name: Spin Speed
      icon: 'mdi:rotate-right'
```
