### ISSUE TITLE
Create dryer dashboard button

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#251]
https://github.com/theglus/Home-Assistant-Config/blob/caf5cef7b46af58a5bbf9ba85b01454ba3a03024/includes/lovelace/views/1_primary.yaml#L339-L342

# Requirements
- [ ] Install [SmartThinQ sensor](https://github.com/ollo69/ha-smartthinq-sensors) HACs integration.
- [ ] TBD

**Comment by theglus** [comment]
Utilize [entity attributes](https://github.com/phrz/lg-washer-dryer-card/blob/1807310cbbb544fe556ab95cbe324ab4faef3e72/dryer-card.yaml#L62). 

```
    card:
      type: entities
      entities:
        - entity: sensor.dryer
          type: attribute
          attribute: current_course
          name: Current Course
          icon: 'mdi:tune-vertical-variant'
        - entity: sensor.dryer
          type: attribute
          attribute: temp_control
          name: Temperature Control
          icon: 'mdi:thermometer'
        - entity: sensor.dryer
          type: attribute
          attribute: dry_level
          name: Dry Level
          icon: 'mdi:air-filter'
```
