### ISSUE TITLE
Create Toggle Nav declutter card

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#294]
# Requirements
- [x] Install HACs Declutter Card
- [x] Add include to `ui-lovelace.yaml`
- [ ] Create `declutter_nav_toggle.yaml`
- [ ] Update General Button
https://github.com/theglus/Home-Assistant-Config/blob/6f32b441321baaa72554dd6ba9d1344d2ee48c7d/includes/lovelace/views/1_primary.yaml#L29-L42
- [ ] Update Entryway Button
https://github.com/theglus/Home-Assistant-Config/blob/6f32b441321baaa72554dd6ba9d1344d2ee48c7d/includes/lovelace/views/1_primary.yaml#L43-L59
- [ ] Update Office Button
https://github.com/theglus/Home-Assistant-Config/blob/6f32b441321baaa72554dd6ba9d1344d2ee48c7d/includes/lovelace/views/1_primary.yaml#L67-L80
- [ ] Update Living Room Button
https://github.com/theglus/Home-Assistant-Config/blob/6f32b441321baaa72554dd6ba9d1344d2ee48c7d/includes/lovelace/views/1_primary.yaml#L84-L97
- [ ] Update Kitchen Button
https://github.com/theglus/Home-Assistant-Config/blob/6f32b441321baaa72554dd6ba9d1344d2ee48c7d/includes/lovelace/views/1_primary.yaml#L101-L114
- [ ] Update Loft Button
https://github.com/theglus/Home-Assistant-Config/blob/6f32b441321baaa72554dd6ba9d1344d2ee48c7d/includes/lovelace/views/1_primary.yaml#L118-L131

### Template
```
declutter_nav_toggle
  - entity: input_select.lighttoggle
    name: false
    icon: "[[nav_icon]]"
    state_styles:
      [[room]]:
      template: nav_button
    template: nav_styles
    tap_action:
      action: call-service
      service: input_select.select_option
      service_data:
      entity_id: input_select.lighttoggle
      option: [[room]]    
```
### Declutter Card
```
type: "custom:declutter-card"
template: declutter_nav_toggle
variables:
  - nav_icon: mdi:bed-king
  - room: Loft
```

# Resources
- [Declutter Card](https://community.home-assistant.io/t/need-help-with-decluttering-card-template/151304)
- [Need help with decluttering card (template)](https://community.home-assistant.io/t/need-help-with-decluttering-card-template/151304)
