### ISSUE TITLE
Create Room Button declutter cards

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#296]
# Requirements
- [x] Create `declutter_room_button.yaml`
- [x] Update Entryway Button
https://github.com/theglus/Home-Assistant-Config/blob/3fd5a0d2b993413ebabd4159f59eec4be3c68634/includes/lovelace/views/1_primary.yaml#L190-L215
- [x] Update Office Button
https://github.com/theglus/Home-Assistant-Config/blob/3fd5a0d2b993413ebabd4159f59eec4be3c68634/includes/lovelace/views/1_primary.yaml#L219-L244
### Template
```
declutter_room_button
  - type: "custom:button-card"
    entity: [[light]]
    custom_fields:
      s2: |
        [[[
          var sensor_state = (states['[[sensor]]'].state);
          if (sensor_state == "on") return "[[message_on]]";
          else return "[[message_off]]" 
        ]]]
    icon: |
      [[[ 
        var sensor_state = (states['[[sensor]]'].state);
        if (sensor_state == "on") 
          return "[[icon_state]]"; 
        else 
          return "[[icon_default]]" 
      ]]]
    name: [[room]]
    template:
      - room_layout
      - room_states
      - room_states_on
      - room
    triggers_update:
      - [[sensor]]
```
### Declutter Card
```
type: "custom:decluttering-card"
template: declutter_room_button
variables:
  - light: light.group_hallway
  - sensor: binary_sensor.front_door
  - message_on: Door is open
  - message_off: Door is closed
  - icon_state: mdi:door-open
  - icon_default: mdi:coat-rack
```

# Resources
- [Declutter Card](https://community.home-assistant.io/t/need-help-with-decluttering-card-template/151304)
- [Need help with decluttering card (template)](https://community.home-assistant.io/t/need-help-with-decluttering-card-template/151304)
