### ISSUE TITLE
Create Temp Button declutter card

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#297]
# Requirements
- [x] Create `declutter_temp_button.yaml`
- [x] Update Living Room Temp Button
https://github.com/theglus/Home-Assistant-Config/blob/3fd5a0d2b993413ebabd4159f59eec4be3c68634/includes/lovelace/views/1_primary.yaml#L248-L315
- [x] Update Kitchen Temp Button
https://github.com/theglus/Home-Assistant-Config/blob/3fd5a0d2b993413ebabd4159f59eec4be3c68634/includes/lovelace/views/1_primary.yaml#L319-L380
- [x] Update Loft Temp Button
https://github.com/theglus/Home-Assistant-Config/blob/3fd5a0d2b993413ebabd4159f59eec4be3c68634/includes/lovelace/views/1_primary.yaml#L385-L445
### Template
```
declutter_temp_button
#################################################################
## Temperature Mini Graph Button
#################################################################
card:
    type: "custom:button-card"
    entity: '[[light]]'
    custom_fields:
      s2: |
        [[[
          var sensor_state = (states['[[hvac]]'].state);
          if (sensor_state == "on") return "[[message_on]]";
          else return "[[message_off]]" 
        ]]]
    icon: |
      [[[ 
        var sensor_state = (states['[[hvac]]'].state);
        if (sensor_state == "on") 
          return "[[icon_state]]r"; 
        else 
          return "[[icon_default]]" 
      ]]]
    label: |
      [[[
        return states['[[sensor_temp]]'].state + '°F'
      ]]]
    name: '[[room]]'
    double_tap_action:
      action: fire-dom-event
      browser_mod:
        command: popup
        title: '[[room]]'
        style:
          hui-grid-card$: |
            #root {
              grid-gap: 0 !important;
            }
        card:
          type: grid
          columns: 1
          square: false
          cards:
            - type: custom:mini-graph-card
              entities:
              - '[[sensor_temp]]'
              color_thresholds:
              - value: 0
                color: '#6aa84f'
              - value: 68
                color: '#f1c232'
              - value: 72
                color: '#e69138'
              - value: 75
                color: '#cc0000'                                                       
              name: Temperature                           
              line_width: 5
              points_per_hour: 2
              align_icon: left
              align_state: right
              align_header: left
              hours_to_show: 24
              show:
                icon: true
              tap_action:
                action: more-info 
    template:
      - room_layout
      - room_states
      - room_states_on
      - room
    triggers_update:
      - '[[hvac]]'
```
### Declutter Card
```
type: "custom:decluttering-card"
template: declutter_temp_button
variables:
  - light: light.group_living_room
  - hvac: switch.switchbot
  - sensor_temp: sensor.temperature_living_room
  - message_on: Heat is on
  - message_off: Heat is off
  - icon_state: mdi:radiator
  - icon_default: mdi:sofa
  - room: Living Room
```

# Resources
- [Declutter Card](https://community.home-assistant.io/t/need-help-with-decluttering-card-template/151304)
- [Need help with decluttering card (template)](https://community.home-assistant.io/t/need-help-with-decluttering-card-template/151304)
