### ISSUE TITLE
Alarm + timer countdown for Google Home devices

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#315]
https://github.com/theglus/Home-Assistant-Config/blob/cd41d00b355a01487880419c8ea0804418586767/includes/lovelace/views/1_primary.yaml#L449-L463

# Requirements
- [ ] Create modified circle template for countdown sensors.
- [ ] Update Lovelace buttons with new template.
- [ ] Add sensor parameters to Lovelace buttons.

# Resources
- [Circle Sensor Card](https://github.com/custom-cards/circle-sensor-card)
```
- type: "custom:button-card"
    entity: fan.kitchen
    name: Dyson
    template:
    - base
    - icon_dyson
    - circle
    - loader
    variables:
    circle_input: >
        [[[
        return entity === undefined ?
            null :
            parseInt(entity.attributes.percentage);
        ]]]
```
