### ISSUE TITLE
Notify if AC = ON during peak usage

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#320]
# Requirements
- [x] Create [notify group](https://www.home-assistant.io/integrations/notify.group/).
- [x] Create automation.

**Trigger**
* If ice_bear state = `cool` or `auto`.

**Conditions**
* During the hours of 4 pm - 9 pm.

**Action**
* Notify Pixel 5.

```
alias: fan notification
description: ''
trigger:
  - platform: state
    entity_id: climate.ice_bear
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
    to: cool
  - platform: time
    at: '16:00:00'
  - platform: state
    entity_id: climate.ice_bear
    to: auto
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
condition: []
action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: climate.ice_bear
                for:
                  hours: 0
                  minutes: 0
                  seconds: 30
                  milliseconds: 0
                state: cool
              - condition: time
                after: '16:00:00'
                before: '21:00:00'
        sequence:
          - service: notify.smartphones
            data:
              message: Ice Bear is cooling.
              title: ⚡Peak Usage Alert
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: climate.ice_bear
                state: auto
                for:
                  hours: 0
                  minutes: 0
                  seconds: 30
                  milliseconds: 0
              - condition: time
                after: '16:00:00'
                before: '21:00:00'
        sequence:
          - service: notify.smartphones
            data:
              message: Ice Bear is in ECO mode.
              title: ⚡Peak Usage Alert
    default: []
mode: single
```

# Resources
* [Notification Integration](https://www.home-assistant.io/integrations/notify/)
* [Alert Integration](https://www.home-assistant.io/integrations/alert/)
