### ISSUE TITLE
Setup CI/CD utilizing Git Pull add-on

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#5]
# Requirements 
```
deployment_key:
  - '-----BEGIN OPENSSH PRIVATE KEY-----'
  - HIDDEN
  - '-----END OPENSSH PRIVATE KEY-----'
deployment_key_protocol: rsa
deployment_user: ''
deployment_password: ''
git_branch: master
git_command: pull
git_remote: origin
git_prune: false
repository: 'ssh://git@git.afola.ovh:2222/home-assistant/home-flamel.git'
auto_restart: true
restart_ignore:
  - ui-lovelace.yaml
  - .gitignore
  - appdaemon/
  - .flake8
  - Pipfile
repeat:
  active: true
  interval: 60
```
# Resources
- [Git Pull](https://github.com/home-assistant/hassio-addons/tree/master/git_pull)
- [Syncing HomeAssistant With GitHub](https://blog.schembri.me/post/syncing-homeassistant-with-github/)
- [Troubleshooting](https://community.home-assistant.io/t/git-pull-addon/23435/54)
