### ISSUE TITLE
Resolve BrowserMod breaking changes

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#570]
# Requirements

- [x] climate_fan.yaml
- [x] light.yaml
- [x] light_color.yaml
- [x] light_nanoleaf.yaml
- [x] volume_speaker.yaml
- [x] declutter_temp_button.yaml
- [x] configuration.yaml 

# Resources
How do I update a popup from the Browser mod 1.5?

If you have used fire-dom-event it's really simple. Just change
```

action: fire-dom-event
browser_mod:
  command: popup
  title: My title
  card:
    type: ...etc...
```

to

```
action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: My title
    content:
      type: ...etc...
```
