### ISSUE TITLE
Conduct clean install + setup on Scruffy

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#616]
# Requirements
## Ubuntu Install
- [x] Install Ubuntu Server.
- [x] Utilize `swap file` instead of `swap partition`. 
- [x] Leverage partitions.
## NFS mount
- [x] Mount NAS to Scruffy.
## Docker
- [x] Install [Docker Engine](https://docs.docker.com/engine/install/ubuntu/).
### Uptime Kuma
- [ ] Create file structure for Uptime Kuma.
``` 
|-- uptime-kuma
	|-- appdata
	|-- docker-compose.yaml
```
- [ ] Create `docker-compose` for Uptime Kuma.
```
---
version: "3"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: unless-stopped

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=mytokengoeshere
```

- [ ] Setup tunnel for `status.planetexpress.casa`.
- [ ] Setup tunnel for `uptime.planetexpress.casa`.

### Cloudflared
- [ ] Create file structure for [Cloudflared](https://github.com/cloudflare/cloudflared).
``` 
|-- cloudflared
	|-- appdata
	|-- docker-compose.yaml
```
- [ ] Create `docker-compose` for Cloudflared.
```
---
version: "3"
services:
  cloudflared:
    image: cloudflare/cloudflared:latest 
    container_name: cloudflared 
    volumes:
    ports:
    restart: unless-stopped
```
- [ ] Setup tunnel for `swtich.planetexpress.casa`.
- [ ] Setup tunnel for `labs.planetexpress.casa`.

### Portainer

- [ ] Create file structure for Portainer.
``` 
|-- portainer
	|-- appdata
	|-- docker-compose.yaml
```
- [ ] Create `docker-compose` for Portainer.
```
---
version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000
```

# Resources
* [Install Docker Engine on Ubuntu](https://docs.docker.com/engine/install/ubuntu/)
* [Uptime Kuma](https://github.com/louislam/uptime-kuma)
* [Cloudflared](https://github.com/cloudflare/cloudflared)
* [Using Cloudflared tunnels](https://www.youtube.com/watch?v=eojWaJQvqiw)
* [Cloudflared as docker compose](https://community.cloudflare.com/t/can-i-use-cloudflared-in-a-docker-compose-yml/407168)
* [Setup NFS mount](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-nfs-mount-on-ubuntu-20-04)
