### ISSUE TITLE
Track issue w/ missing Sidebar Card

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#618]
# Details

```
background: var(--background-image)
kiosk_mode:
  hide_header: true
sidebar:
  hideTopMenu: true
  digitalClock: true
  twelveHourVersion: true
  period: false
  date: true
  dateFormat: dddd, MMMM Do
  width:
    mobile: 0
    tablet: 25
    desktop: 25
  sidebarMenu:
    - action: navigate
      navigation_path: "/lovelace/default_view"
      name: "Home"
      icon: "mdi:home"
      active: true
    - action: navigate
      navigation_path: "/lovelace/winston"
      name: "Winston"
      icon: "mdi:robot-vacuum-variant"
      active: true
    - action: navigate
      navigation_path: "/lovelace/ha"
      name: "System"
      icon: "mdi:home-assistant"
      active: true
  template: |
    <li>The air quality in Dogpatch is {{states('sensor.u_s_air_pollution_level')}} with an AQI of {{states('sensor.aqi')}}.</li>
  style: |
    :host {
        --sidebar-background: rgba(0,0,0,.3);
    }
button_card_templates: !include_dir_named includes/lovelace/button_card_templates
decluttering_templates: !include_dir_named includes/lovelace/decluttering_templates
title: Loft
views: !include_dir_list includes/lovelace/views
```

![Missing Sidecard](https://user-images.githubusercontent.com/2943783/231296100-8d9d4e9a-084a-46fd-823a-7e5dfbdf5446.png)

# Resources
* [Sidebar Card](https://github.com/DBuit/sidebar-card)
* https://github.com/DBuit/sidebar-card/issues/83#issuecomment-1504149666
