### ISSUE TITLE
Integrate Roborock S4 in HA

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#63]
# Requirements
- [ ] Obtain device token
- [ ] Look-u device IP
- [ ] Create `secrets`
- [ ] Update `configuration.yaml` with `vacuum` config

```
vacuum:
  - platform: xiaomi_miio
    host: !secret winston_host
    token: !secret winston_token
    name: Winston
```

# Resources
- [HA Xiaomi Miio](https://www.home-assistant.io/integrations/xiaomi_miio/)
- [Integrating the Roborock S4 in Home Assistant ](https://aarongodfrey.dev/home%20automation/integrating_the_roborock_s4_in_home_assistant/)
- [Home Assistant Roborock in detail step by step](https://home-automations.net/home-assistant-roborock-in-detail-step-by-step/)
