### ISSUE TITLE
script.clean_kitchen

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#86]
```
service: vacuum.send_command
data:
  entity_id: vacuum.winston
  command: app_segment_clean
  params: [18]
```
