### ISSUE TITLE
script.clean_office

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#87]
```
service: vacuum.send_command
data:
  entity_id: vacuum.winston
  command: app_segment_clean
  params: [19]
```
