### ISSUE TITLE
script.clean_living_room

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#88]
```
service: vacuum.send_command
data:
  entity_id: vacuum.winston
  command: app_segment_clean
  params: [17]
```
