### ISSUE TITLE
script.clean_bathroom

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#89]
```
service: vacuum.send_command
data:
  entity_id: vacuum.winston
  command: app_segment_clean
  params: [20]
```
