### ISSUE TITLE
script.clean_hallway

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#90]
```
service: vacuum.send_command
data:
  entity_id: vacuum.winston
  command: app_segment_clean
  params: [16]
```
